services:
  - type: worker
    name: telegram-hunter-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_runner.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
